node-defaults: &NODE
  working_directory: ~/app
  docker:
    - image: celohq/node10-gcloud:v3
  environment:
    # To avoid ENOMEM problem when running node
    NODE_OPTIONS: '--max-old-space-size=4096'

checkout-workspace-defaults:
  - &CHECKOUT-WORKSPACE
    attach_workspace:
      at: ~/app

version: 2

workflows:
  version: 2
  CI:
    jobs:
      - npm-install
      - test-ng:
          requires:
            - npm-install

jobs:
  # NPM install
  npm-install:
    <<: *NODE
    steps:
      - checkout
      - restore_cache:
          keys:
          - website-dependencies-{{ checksum "package.json" }}
          - website-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: website-dependencies-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  # Tests
  test:
    <<: *NODE
    steps:
      - checkout
      - *CHECKOUT-WORKSPACE
      - run: npm run test
      - persist_to_workspace:
          root: .
          paths:
            - coverage